post_install() {
  # detect user. If root, do nothing.
  user="${SUDO_USER}"
  if [[ "${user}" != "" ]]; then
    # install vim-plug
    curl -fLo /home/${user}/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    # change ownership of files
    chown -Rh ${user}:users /home/${user}/.vim/

    su ${user}
    # will this work with wakatime??
    vim +PlugInstall +qall </dev/tty > /dev/tty
  fi
}
