# common variables
url='https://github.com/brisvag/arch'
arch=('any')

# autogenerated variables
pkgname="brisvag-${name}"
# backslash (and later eval) are necessary because pkgdir is not defined until later
home="\${pkgdir}${HOME}"
rootdir=${PWD}

# version is rX.Y: X=number of revisions, Y=last commit hash
# important: need to keep also this file into account for revision number!
# however, only count commits of this file AFTER the package was first created
version() {
  this="${rootdir}/../common.sh"
  startdate=$(git log --follow --date=short --pretty=format:%ad --diff-filter=A "${rootdir}")
  ncommits=$(git shortlog -s --since="${startdate}" "${rootdir}" "${this}" | awk '{n += $1}; END{print n}')
  lasthash=$(git log -n 1 --pretty=format:%h -- "${rootdir}" "${this}")
  printf "r%s.%s" "${ncommits}" "${lasthash}"
}
pkgver=$(version)
pkgrel=1

# use X.txt and X.install (if they exist) for deps an hooks
if [[ -f "${name}.txt" ]]; then
  # grep to ignore comments
  depends=($(grep -v "^#" "${name}.txt"))
fi

if [[ -f "${name}.install" ]]; then
  install="${name}.install"
fi

package() {
  # package dotfiles
  if [[ -d "${rootdir}"/dotfiles ]]; then
    local home=$(eval echo "${home}")
    mkdir -p "${home}"
    cp -a "${rootdir}"/dotfiles "${home}"
  fi
  return 0
}
