# common variables
url='https://github.com/brisvag/arch'
arch=('x86_64')

# autogenerated variables
pkgname="brisvag-${name}"
# backslash (and later eval) are necessary because pkgdir is not defined until later
home="\${pkgdir}${HOME}"
rootdir=${PWD}

# add all files in this directory to the package and skip sha256
#source=($(find ./HOME -mindepth 1 -maxdepth 1))
#for i in $(seq 1 ${#source[@]}); do
#  sha256sums+=(SKIP)
#done

# use X.txt and X.install (if they exist) for deps an hooks
if [[ -f "${name}.txt" ]]; then
  # grep to ignore comments
  depends=($(grep -v "^#" "${name}.txt"))
fi

if [[ -f "${name}.install" ]]; then
  install="${name}.install"
fi


# copy config files and directories to the right places
#install_="install -D -o brisvag -g brisvag --verbose --backup --compare -m644"
#installX="install -D -o brisvag -g brisvag --verbose --backup --compare -m750"
#installD="install -d -o brisvag -g brisvag --verbose --backup --compare"

package() {
  # package dotfiles
  local home=$(eval echo "${home}")
  mkdir -p "${home}"
  cp -a "${rootdir}"/HOME "${home}"

  return 0
}