#!/bin/bash

if [ "$(iw dev wlp3s0 link)" == "Not connected." ]; then
	/.config/i3/iface;
else
	echo "$(iw dev wlp3s0 link | grep SSID | cut -d ' ' -f 2-) - $(~/.config/i3/iface) - $(iw dev wlp3s0 link | grep signal | cut -d ' ' -f 2-)"
fi
