post_install() {
  # move old pacman.conf ot of the way and replace it
  if [[ -f "/etc/pacman.conf" ]]; then
    mv "/etc/pacman.conf" "/etc/pacman.conf.pacbak"
    cp "/etc/pacman.conf.template" "/etc/pacman.conf"
  fi

  # include post_upgrade stuff
  post_upgrade
}

post_upgrade() {
  chmod -R 755 "/etc/pacman.d/hooks.bin/"
}

post_remove() {
  # restore old pacman.conf
  if [[ -f "/etc/pacman.conf.pacbak" ]]; then
    mv "/etc/pacman.conf.pacbak" "/etc/pacman.conf"
  fi
}
